### ISSUE TITLE
关于服务部署

### ISSUE THREAD

**Issue by Germiniku** [deepops-ai/deepops#183]
我后续有时间考虑完善服务容器一键部署，有什么看法吗
我考虑放到`deploy`这个顶层目录

**Comment by sunface** [comment]
可以的，没问题，以后要是有调整再修改~~

**Comment by sunface** [comment]
话说你对 datav 了解不，哈哈～～要是有啥疑问可以跟我沟通下

**Comment by Germiniku** [comment]
> 话说你对 datav 了解不，哈哈～～要是有啥疑问可以跟我沟通下

哈哈哈 还是不太了解

**Comment by Germiniku** [comment]
方便留个联系沟通下吗

**Comment by sunface** [comment]
你加我微信， isunface

**Comment by sunface** [comment]
我新支持了 sqlite，你可以把配置项的 connect_to 修改为 sqlite，这个比 mysql 方便很多，也好删除数据进行测试
